export const MULTICALL_ERRORS = {
  SIMULTANEOUS_INVOCATIONS: new Error(
    'Another execution was triggered during processing.'
  ),
};
